version: 5
common:
  train_log_path: C:\Users\David\Downloads\simod-softwarex\config\academic\..\..\event-logs\AcademicCredentials_train.csv.gz
  test_log_path: C:\Users\David\Downloads\simod-softwarex\config\academic\..\..\event-logs\AcademicCredentials_test.csv.gz
  log_ids:
    case: case_id
    activity: activity
    resource: resource
    start_time: start_time
    end_time: end_time
    enabled_time: enabled_time
    enabling_activity: enabling_activity
    available_time: available_time
    estimated_start_time: estimated_start_time
    batch_id: batch_instance_id
    batch_type: batch_instance_type
  process_model_path: null
  num_final_evaluations: 10
  evaluation_metrics:
  - THREE_GRAM_DISTANCE
  - TWO_GRAM_DISTANCE
  - ABSOLUTE_EVENT_DISTRIBUTION
  - RELATIVE_EVENT_DISTRIBUTION
  - CIRCADIAN_EVENT_DISTRIBUTION
  - ARRIVAL_EVENT_DISTRIBUTION
  - CYCLE_TIME_DISTRIBUTION
  - CIRCADIAN_WORKFORCE_DISTRIBUTION
  use_observed_arrival_distribution: false
  clean_intermediate_files: true
  discover_data_attributes: false
preprocessing:
  multitasking: false
  enable_time_concurrency_threshold: 0.5
  concurrency_df: 0.9
  concurrency_l2l: 0.9
  concurrency_l1l: 0.9
control_flow:
  optimization_metric: two_gram_distance
  num_iterations: 30
  num_evaluations_per_iteration: 5
  gateway_probabilities: discovery
  mining_algorithm: sm1
  epsilon: !!python/tuple
  - 0.05
  - 0.4
  eta: !!python/tuple
  - 0.2
  - 0.7
  replace_or_joins:
  - true
  - false
  prioritize_parallelism: true
resource_model:
  optimization_metric: circadian_event_distribution
  num_iterations: 40
  num_evaluations_per_iteration: 5
  discovery_type: differentiated_by_resource
  discover_prioritization_rules: false
  discover_batching_rules: false
  granularity: 60
  confidence: !!python/tuple
  - 0.5
  - 0.85
  support: !!python/tuple
  - 0.05
  - 0.5
  participation: 0.4
extraneous_activity_delays:
  optimization_metric: RELATIVE_EMD
  discovery_method: COMPLEX
  num_iterations: 20
  num_evaluations_per_iteration: 3
