"""initial: create ngram_index

Revision ID: b05da67dcff2
Revises: 
Create Date: 2025-05-19 02:31:15.084352

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b05da67dcff2'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ngram_index',
    sa.Column('process_id', sa.String(length=36), nullable=False),
    sa.Column('prefix', sa.String(length=255), nullable=False),
    sa.Column('marking', sa.String(length=1024), nullable=False),
    sa.PrimaryKeyConstraint('process_id', 'prefix')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ngram_index')
    # ### end Alembic commands ###
