"""Update ngram_index schema

Revision ID: b6186d75287d
Revises: b05da67dcff2
Create Date: 2025-06-08 21:29:28.026786

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b6186d75287d'
down_revision: Union[str, None] = 'b05da67dcff2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ngram_index',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('process_id', sa.String(length=36), nullable=False),
    sa.Column('prefix', sa.Text(), nullable=False),
    sa.Column('marking', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.execute("CREATE INDEX idx_process_prefix ON ngram_index (process_id, prefix(512))")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_process_prefix', table_name='ngram_index')
    op.drop_table('ngram_index')
    # ### end Alembic commands ###
